feat: Auto bump chart version if not specified
newrelic/helm-charts pull request #118
Opened 2020-09-04 16:31 UTC by gsanchezgavier

#### Is this a new chart
No
#### What this PR does / why we need it:
It modify the version bumper GHA to increase the chartVersion by 1 if has not been specified.
This way external repos like nri-prometheus could automate the process of updating the app version without knowing the chart version.
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md
- [ ] Title of the PR starts with chart name (e.g. `[mychartname]`)

2020-09-04 16:32 UTC, gsanchezgavier commented
@jorik

2020-09-15 08:18 UTC, jorik requested changes
LGTM, but can you describe the new behaviour in the chart-version-bumper readme?

2020-09-15 09:10 UTC, jorik commented on README.md
> +`chart_version`: (optional) If specified the chart version will be set with this value. If empty the version of the chart will be bumped by 1 e.g: 1.2.19 -> 1.2.20
```suggestion
`chart_version`: (optional) If specified the chart version will be set with this value. If left empty the patch version of the chart will be bumped by 1, e.g: 1.2.19 -> 1.2.20
```

2020-09-15 09:42 UTC, jorik approved these changes

2020-09-15 10:49 UTC, merged