[nr-ebpf-agent] Add option to configure protocols, update readme with usage details
newrelic/helm-charts pull request #1436
Opened 2024-07-24 01:43 UTC by benkilimnik

Also updates the agent and client images to the latest version.

#### Is this a new chart

#### What this PR does / why we need it:

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[mychartname]`)

2024-07-24 19:00 UTC, ramkrishankumarN submitted a review, later dismissed

2024-07-24 19:19 UTC, kpattaswamy approved these changes

2024-07-26 17:29 UTC, dbudziwojskiNR requested changes

2024-07-26 17:29 UTC, dbudziwojskiNR commented on charts/nr-ebpf-agent/README.md
>  | Key | Type | Default | Description |
This table should be autogenerated with `helm-docs` which pulls from `values.yaml`.

2024-07-26 17:29 UTC, dbudziwojskiNR commented on charts/nr-ebpf-agent/README.md
Please create a `README.md.gotmpl` that templates this README. As an example, please see this file: https://github.com/newrelic/helm-charts/blob/master/charts/nr-k8s-otel-collector/README.md.gotmpl

2024-07-26 17:43 UTC, dbudziwojskiNR commented
One final tweak so you don't have to do this down the line, but you should consider replacing the existing NR logo with the following new one: `<a href="https://opensource.newrelic.com/oss-category/#community-plus"><picture><source media="(prefers-color-scheme: dark)" srcset="https://github.com/newrelic/opensource-website/raw/main/src/images/categories/dark/Community_Plus.png"><source media="(prefers-color-scheme: light)" srcset="https://github.com/newrelic/opensource-website/raw/main/src/images/categories/Community_Plus.png"><img alt="New Relic Open Source community plus project banner." src="https://github.com/newrelic/opensource-website/raw/main/src/images/categories/Community_Plus.png"></picture></a>
`

This snippet has the new logos and automagically changes on light and dark mode 💯

2024-07-26 21:36 UTC, dbudziwojskiNR approved these changes

2024-07-26 21:36 UTC, merged