[nr-k8s-otel-collector] Honor the LowDataMode toogle from the common-library
newrelic/helm-charts pull request #1472
Opened 2024-09-03 14:32 UTC by kang-makes

#### Is this a new chart
No

#### What this PR does / why we need it:
The value for `lowDataMode` was hard coded at values level so a user cannot set the value if you not go deep down to the chart and patch it.

This change has its own implementation of the lowDataMode helper that defaults to `true` while honoring the behaviour of the common-library of setting a value a `global` level.

#### Which issue this PR fixes

#### Special notes for your reviewer:

#### Checklist
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[mychartname]`)

2024-10-01 01:58 UTC, csongnr approved these changes

2024-10-02 17:34 UTC, dbudziwojskiNR requested changes

2024-10-02 17:34 UTC, dbudziwojskiNR commented on charts/nr-k8s-otel-collector/values.yaml
>  # -- (bool) Send only the [metrics required](https://github.com/newrelic/helm-charts/tree/master/charts/nr-k8s-otel-collector/docs/metrics-lowDataMode.md) to light up the NR kubernetes UI, this agent
After this change, wouldn't `lowDataMode` be true if unset? If so, we should update this wording.

2024-10-11 20:28 UTC, dbudziwojskiNR commented on charts/nr-k8s-otel-collector/values.yaml
>  # -- (bool) Send only the [metrics required](https://github.com/newrelic/helm-charts/tree/master/charts/nr-k8s-otel-collector/docs/metrics-lowDataMode.md) to light up the NR kubernetes UI, this agent
@kang-makes Bumping this :) Thanks!

2025-01-08 19:12 UTC, dbudziwojskiNR submitted a review, later dismissed

2025-01-08 19:22 UTC, dbudziwojskiNR approved these changes

2025-01-08 19:23 UTC, merged