[nr-ebpf-agent] Update README.md
newrelic/helm-charts pull request #1478
Opened 2024-09-11 01:47 UTC by truegilb

Fixed typo.

#### Is this a new chart
No

#### What this PR does / why we need it:
Fixed a typo in README.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md
- [ ] Title of the PR starts with chart name (e.g. `[mychartname]`)

2024-09-13 17:22 UTC, dbudziwojskiNR approved these changes

2024-09-13 17:23 UTC, dbudziwojskiNR requested changes
You would need to bump the version of this chart to pass tests.

2024-09-13 17:24 UTC, dbudziwojskiNR commented
You also need approval from someone on the EBPF team to approve this.

2024-09-14 00:25 UTC, benkilimnik approved these changes

2024-09-18 22:32 UTC, kpattaswamy approved these changes

2024-09-18 22:33 UTC, kpattaswamy commented
@dbudziwojskiNR I think you may need to also approve again.

2024-09-18 22:34 UTC, dbudziwojskiNR approved these changes

2024-09-18 22:35 UTC, merged