[newrelic-logging] add labels to metrics output to enable entity synthesis
newrelic/helm-charts pull request #1547
Opened 2024-12-12 10:22 UTC by rohit-bandlamudi-nr

#### Is this a new chart
Yes

#### What this PR does / why we need it:

This PR adds two additional labels to the newrelic-logging chart's configmap. These labels are needed for entity synthesis.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Chart Version bumped
- [ ] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[mychartname]`)

2024-12-12 10:24 UTC, voorepreethi submitted a review, later dismissed

2024-12-12 11:18 UTC, voorepreethi commented on charts/newrelic-logging/templates/configmap.yaml
> +    {{ printf "add_label            namespace %s" .Release.Namespace | nindent 8}}
Can we move this to helper.tpl for better encapsulation

2024-12-18 07:20 UTC, voorepreethi approved these changes

2024-12-18 10:42 UTC, voorepreethi submitted a review, later dismissed

2025-01-07 09:07 UTC, voorepreethi approved these changes

2025-01-07 09:09 UTC, voorepreethi reviewed
Workflows are failing. Please check

2025-02-03 12:28 UTC, jsubirat submitted a review, later dismissed
Nice stuff 👍

2025-02-03 12:56 UTC, maya-jha requested changes

2025-02-03 12:56 UTC, maya-jha commented on charts/newrelic-logging/Chart.yaml
> +version: 1.23.6-beta
Why are we using beta here?

2025-02-03 12:56 UTC, maya-jha commented on charts/newrelic-logging/templates/_helpers.tpl
> +[INPUT]
Why don't we just keep this in values.yaml for better visibility.

2025-02-03 13:28 UTC, maya-jha commented on charts/newrelic-logging/values.yaml
> +          sendMetrics    true
Do we need to enable this for fluent bit? It seems to me that its specific for sending output plugin related metrics. : https://github.com/newrelic/newrelic-fluent-bit-output/pull/142/files @jsubirat

2025-02-05 14:10 UTC, rohit-bandlamudi-nr commented on charts/newrelic-logging/templates/_helpers.tpl
> +[INPUT]
We are enabling sending of metrics by default. We don't want this to be configurable by the user using the values file. Basically, disabling metrics should not be an option

2025-02-05 14:13 UTC, rohit-bandlamudi-nr commented on charts/newrelic-logging/values.yaml
> +          sendMetrics    true
yes, sendMetrics are defaulted to false in the newrelic-fluentbit-output repo. We can change that to true. Until then, we have set this to true for testing

2025-02-05 14:18 UTC, rohit-bandlamudi-nr commented on charts/newrelic-logging/Chart.yaml
> +version: 1.23.6-beta
We want to release this as a beta version and test the entity synthesis and forwarding of metrics (if possible, we want to test this with fleet control and agent control as well)

2025-02-05 14:36 UTC, nr-rkallempudi submitted a review, later dismissed

2025-02-06 06:00 UTC, rohit-bandlamudi-nr commented on charts/newrelic-logging/values.yaml
> +          sendMetrics    true
> Do we need to enable this for fluent bit? It seems to me that its specific for sending output plugin related metrics. : https://github.com/newrelic/newrelic-fluent-bit-output/pull/142/files @jsubirat

Yeah, note that , these metrics are not required for creation of fluentbit entity. But we will be missing on some key metrics forwarded by the newrelic fluentbit output plugin that are used to power few charts on the fluentbit entity view

2025-02-10 09:17 UTC, maya-jha commented on charts/newrelic-logging/values.yaml
> +          sendMetrics    true
Discussed offline with @nr-rkallempudi and Joshua and we aligned on not changing anything related fluent bit output plugin metrics. The [metrics added by fluent bit output plugin](https://github.com/newrelic/newrelic-fluent-bit-output/blob/master/metrics/constants.go#L5C1-L9) are not being used for fluent bit dashboard AFAIK.

2025-02-11 14:11 UTC, closed without merging