[newrelic-logging] Made fluent-bit.conf and parsers.conf ConfigMap configurable from values.yaml file
newrelic/helm-charts pull request #593
Opened 2021-11-17 18:30 UTC by bpschmitt

#### Is this a new chart

No

#### What this PR does / why we need it:

The changes in this PR provide users the ability to customize the fluent-bit.conf and parsers.conf files using the values.yaml file. Previously, this was statically set in the configmap.yaml file. This will provide much better flexibility for custom fluent-bit configurations.

#### Which issue this PR fixes

A cleanup and continuation of https://github.com/newrelic/helm-charts/pull/551 (previously closed by me).

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] Chart Version bumped
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. `[mychartname]`)

2021-11-18 14:56 UTC, jsubirat approved these changes

2021-11-18 15:21 UTC, jsubirat requested changes
Hey @bpschmitt , can you also increase the versions in `nri-bundle`?

2021-11-18 15:29 UTC, bpschmitt commented
thanks @jsubirat - yes, a PR to the `nri-bundle` is next.

2021-11-19 16:34 UTC, bpschmitt commented
`nri-bundle` update: https://github.com/newrelic/helm-charts/pull/599

2021-11-19 17:01 UTC, gsanchezgavier commented
Hi @jsubirat due to some pipeline limitations each chart release has to be done in separates PR. I don't have the exact details but issues might happen if want to revert commits from multiple releases.

2021-11-19 17:04 UTC, jsubirat approved these changes

2021-11-22 15:47 UTC, bpschmitt commented
@jsubirat reminder to merge this.

2021-11-23 13:41 UTC, merged

2021-11-23 13:52 UTC, kang-makes commented
This PR superseeds my POC (https://github.com/newrelic/helm-charts/pull/544) then and it could be closed, right?

2021-11-23 14:35 UTC, jsubirat commented
Indeed, this one allow doing the same as #544 , so that one can be closed.