[newrelic-infrastructure] Add support for custom labels
newrelic/helm-charts pull request #629
Opened 2021-12-23 03:23 UTC by drewrm

#### Is this a new chart

No

#### What this PR does / why we need it:

The purpose of this change is to allow user to add custom labels, for
example to comply with policies that specify all kubernetes objects must have
standard set of labels. For example our standard requires we add a `team` label

#### Checklist

- [ x ] Chart Version bumped
- [ x ] Variables are documented in the README.md
- [ x ] Title of the PR starts with chart name (e.g. `[mychartname]`)

2021-12-23 03:23 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/newrelic/helm-charts?pullRequest=629) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/newrelic/helm-charts?pullRequest=629) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/newrelic/helm-charts?pullRequest=629) it.</sub>

2021-12-23 10:48 UTC, gsanchezgavier requested changes
Thanks for the contribution!! There is an issue with the appVersion

2021-12-23 10:48 UTC, gsanchezgavier commented on charts/newrelic-infrastructure/templates/_helpers.tpl
> +  {{- if .Values.customLabels }}
I would expect local configuration take precedence over global ones, but I see this behavior in the rest of globals here. @roobre  wdyt?

2021-12-23 10:48 UTC, gsanchezgavier commented on charts/newrelic-infrastructure/templates/serviceaccount.yaml
> +  labels: {{ include "newrelic.labels" . | indent 4 }}
thanks for fixing this

2021-12-23 10:48 UTC, gsanchezgavier commented on charts/newrelic-infrastructure/Chart.yaml
> +appVersion: 2.8.4
this version should be a valid nri-kubernetes [released](https://github.com/newrelic/nri-kubernetes/releases) version 
```suggestion
appVersion: 2.8.3
```

2021-12-23 16:07 UTC, gsanchezgavier commented on charts/newrelic-infrastructure/templates/_helpers.tpl
> +  {{- if .Values.customLabels }}
Could you change this logic so both labels are added, meaning global labels will be added to all charts and local labels will be added just in this chart resources.

2022-01-14 13:54 UTC, roobre commented
Closing as support for custom labels has been implemented in the v3 chart: https://github.com/newrelic/helm-charts/pull/624

2022-01-14 13:54 UTC, closed without merging