[newrelic-logging]: Add Allow extraVolumes/extraVolumeMounts configuration options
newrelic/helm-charts pull request #960
Opened 2022-09-27 23:32 UTC by axilleastr

#### Is this a new chart
No.

#### What this PR does / why we need it:
Adds two configuration options for the `[newrelic-logging]` chart:
* extraVolumeMounts
* extraVolumes

#### Which issue this PR fixes
  - fixes https://github.com/newrelic/helm-charts/issues/956

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[mychartname]`)

2022-09-27 23:32 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/newrelic/helm-charts?pullRequest=960) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/newrelic/helm-charts?pullRequest=960) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/newrelic/helm-charts?pullRequest=960) it.</sub>

2022-10-20 04:50 UTC, michaelsilver commented
Friendly bump on this PR :)

2022-11-08 15:53 UTC, jsubirat requested changes
Can you please address these little comments? Thanks!

2022-11-08 15:53 UTC, jsubirat commented on charts/newrelic-logging/values.yaml
> +#   mountPath: /run/log/journal
Please also add a tree for Windows:
```
windows:
    extraVolumes: []
    extraVolumeMounts: []
```

In the future, we will move all the windows-related values here (such as the `windowsNodeSelector`, `windowsOsList`, `enableWindows`...).

2022-11-08 18:33 UTC, bmcfeely commented on charts/newrelic-logging/templates/daemonset.yaml
> +          {{- if .Values.extraVolumeMounts }}
@jsubirat would it be harmful to merge this, and then create another PR for windows? (just so the customer can get what they need sooner)

2022-11-14 14:53 UTC, jsubirat commented on charts/newrelic-logging/templates/daemonset.yaml
> +          {{- if .Values.extraVolumeMounts }}
This also works for  me, let me get this merged then

2022-11-14 14:54 UTC, jsubirat approved these changes

2022-11-14 14:54 UTC, merged

2022-11-14 16:01 UTC, axilleastr commented on charts/newrelic-logging/templates/daemonset.yaml
> +          {{- if .Values.extraVolumeMounts }}
hm, @jsubirat, it seems that release failed due to a chart version conflict i guess (?) 
https://github.com/newrelic/helm-charts/actions/runs/3462547940/jobs/5781589624
Should we bump up newrelic-logging chart's version?